version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zodiax
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - '4000:4000'
      - '5555:5555'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/zodiax
    volumes:
      - ./prisma:/app/prisma

volumes:
  postgres-data:
